### ISSUE TITLE
Hire Us UI element is hard to see

### ISSUE THREAD

**Issue by burrrata** [raid-guild/dot-org#21]
On the https://raidguild.org/#manifesto page in the "Our Services" section the "Hire Us" button is practically invisible (at least on my machine). Seems like an important button / call to action. Might want to make it stand out a bit?

![hire-us](https://user-images.githubusercontent.com/42473928/75805212-67977480-5d4f-11ea-8dc6-816dca1e467f.gif)

**Comment by skuhlmann** [comment]
That is funny - Makes it hard to hire us!
