### ISSUE TITLE
Check wallet balance before allowing to click on pay

### ISSUE THREAD

**Issue by lucascerro** [raid-guild/dot-org#60]
Disabled text could be something like "not enough funds" and auxiliary text "You need 300 DAI to book a consultation"

**Comment by lucascerro** [comment]
This issue also happen both on DAOshop and raiguild/hire

**Comment by brossetti1** [comment]
https://github.com/raid-guild/dot-org/pull/68

let me know if you want anything changed 🥂

**Comment by brossetti1** [comment]
https://github.com/raid-guild/daoshop/pull/16 daoshop pr

**Comment by lucascerro** [comment]
> 
> 
> #68
> 
> let me know if you want anything changed 🥂 - ill open the dao shop pr in a bit here

Sorry, I had not seen your reply.

If a user clicks on the pay button (to transact 300 DAI + gas) and does not have enough gas for the transaction, the metamask preview shows an absurd gas cost (~$900-$1000). To avoid this error, some method of checking for funds before opening metamask could be used.

I don't know if this is the best solution, but the end goal would be to avoid the super-expensive previews when the user doesn't have enough eth.

**Comment by lucascerro** [comment]
example:
![image](https://user-images.githubusercontent.com/49558/106225459-ec8b4800-61c3-11eb-9a79-81f8e8aee4e7.png)

**Comment by lucascerro** [comment]
Ideally, metamask should open, display correct gas cost and throw an alert for insufficient eth. 

If not possible, then next best thing would be to alert the user he doesn't have enough eth instead of opening the popup.

A third, less preferable option would be to warn the user that gas costs might show up weird if they don't have enough eth for gas.

**Comment by lucascerro** [comment]
@brossetti1

**Comment by brossetti1** [comment]
tagging @manolingam as I am currently preoccupied with work obligations unfortunately :(

also noting that we merged [#68](https://github.com/raid-guild/dot-org/pull/68) a while back for this one

**Comment by lucascerro** [comment]
ok, thx! We're working on v2 of the form, so I'll close the issue for now
